services:
  postgres:
    image: postgres:16-alpine
    container_name: rate-limiter-postgres
    environment:
      POSTGRES_DB: ratelimiter
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ratelimiter
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d ratelimiter"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rate-limiter-network

  redis:
    image: redis:7-alpine
    container_name: rate-limiter-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./src/main/resources/redis/scripts:/scripts:ro
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rate-limiter-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rate-limiter-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ratelimiter
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ratelimiter
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - rate-limiter-network

volumes:
  postgres_data:
  redis_data:

networks:
  rate-limiter-network:
    driver: bridge
